# dataset parameters
dataset_parameters:
  database_folder: 'database/datasets'  # datasets location

# model settings
model:
  time_start: -1  # starting time (if -1 take entire dataset)
  time_stop : -1  # stopping time (if -1 take entire dataset)

# wrapper parameters:
wrapper:
  dir:  'runs/...'         # location of model run
  timestep: 1              # size of timesteps (in hours)
  call_xbeach_inter:  168  #  xbeach is called during inter-storm periods every X hours (default: 168, i.e. 1 week)

# xbeach parameters
xbeach:
  version: '1.24'  # version of xbeach used

# thermal moodel parameters
thermal:
  with_solar      : True  # include short wave solar radiation in thermal computation step
  with_longwave   : True  # include longwave radiation (incoming & outgoining) in thermal computation step
  with_convective : True  # include convective heat transfer in thermal computation step
  with_latent     : True  # include latent heat in thermal computation step

# output
output:
  output_res  : 24  # temporal resolution of output variables in hours (i.e., model outputs given variable names every X hours)
  output_var  : ["bath", "al_depth"]  # list of output variables