# dataset parameters
dataset_parameters:
  database_folder: 'database/datasets'  # datasets location

# model settings
model:
  nx: 100  # number of points in x-direction
  ny: 0    # number of points in y-direction
  len_x: 4000  # length of the grid in x-direction (m), starting from the baseline (x=0)
  len_y: 0    # length of the grid in y-direction (m)
  time_start: '01-08-2020'  # DD-MM-YY starting time (if -1 take entire dataset)
  time_end : '01-09-2020' # DD-MM-YY stopping time (if -1 take entire dataset)
  timestep: 1              # size of timesteps (in hours)
  call_xbeach_inter:  168  #  xbeach is called during inter-storm periods every X (wrapper) timesteps (default: 168, i.e. 1 week)
  grid_orientation: 88.14  # [degrees], grid orientation with respect to east. The current orientation is calculated in the 'generate_bathymetry.ipynb' notebook

# wrapper parameters:
wrapper:
  dir:  'runs/...'         # location of model run
  bathy_path: "database/bathy.txt"  # path to initial bathymetry
  bathy_grid_path: "database/bathy_grid.txt"  # path to grid corresponding to initial bathymetry
  
# xbeach parameters
xbeach:
  # version: '1.24'  # version of xbeach used
  xfile:   'x.grd'   # file used for the grid (x-direction)
  yfile:   'y.grd'   # file used for the grid (y-direction)
  depfile: 'bed.dep'  # file used for the bed
  tstop:   '3600'    # length of xbeach simulation (in seconds), should be the same as model.timestep
  thetamin: '-90'  # minimum angle
  thetamax: '90'   # maximum angle
  dtheta:   '15'     # bin width
  wbctype: 'jons'   # type of wave boundary condition
  bcfile:  'filelist.txt'  # file ocntaining the bc specifications
  reposeangle: 35  # [degrees] angle of repose used in xbeach (placeholder)
  rho_sea_water : 1025  # [kg/m3] density (sea) water
  visc_kin      : 0.000006  # [m2/s] kinematic viscosity sea water (placeholder)
  sea_ice_threshold: 0.20  # Only run xbeach if sea ice fraction is below threshold, otherwise assume all wave action attenuated

# thermal moodel parameters
thermal:
  # general
  with_solar      : True  # include short wave solar radiation in thermal computation step
  with_longwave   : True  # include longwave radiation (incoming & outgoining) in thermal computation step
  with_convective : True  # include convective heat transfer in thermal computation step
  with_latent     : True  # include latent heat in thermal computation step\
  with_sea_ice    : True  # indicates whether or not the thermal component is run during the period in which the sea is covered with ice
  
  # model properties
  dt: 360  # [s] timestep used in the thermal model on the temporal subgrid
  grid_resolution : 30  # number of points for each 1D thermal model
  max_depth       : 3  # [m], the maximum depth of the 1D thermal model
  # dz_max          : 10 # [m/s/m] Maximum bed level change due to avalanching
  T_melt          : 273.15  # [K] Melting temperature at the interface of water/air and bluff

  # water properties
  wl_switch       : 0  # [m], water level relative to outputted local water level at which is switched from wet to dry (positive means higher than output water level)
  L_water_ice     : 334000000 # [J/m3] latent heat of fusion water-ice
  rho_water       : 1000  # [kg/m3] water density
  rho_ice         : 971  # [kg/m3] density ice
  # c_sea_water     : ...  # [J/K] heat capacity for seawater
  # k_sea_water     : ... #  [W/m/K] thermal conductivity for sea water

  # soil properties
  rho_soil_frozen   : 1500   # [kg/m3] density frozen soil, placeholder (placeholder)
  rho_soil_unfrozen : 1500   # [kg/m3] density unfrozen soil, placeholder (placeholder)
  nb              : 0.65  # [-] ground ice content (Ravens et al, 2023: 0.65 - 0.45)
  c_soil_frozen   : 4600000  # [J/K/m3] heat capacity for frozen soil (Ravens et al, 2023)
  c_soil_unfrozen : 7000000  # [J/K/m3] heat capacity for unfrozen soil (Ravens et al, 2023)
  k_frozen_soil   : 2.7 #  [W/m/K] thermal conductivity for frozen soil (Ravens et al, 2023: 0.7 - 2.7)
  k_unfrozen_soil : 1.5 #  [W/m/K] thermal conductivity for unfrozen soil (Ravens et al, 2023: 0.6 - 1.5)


# output
output:
  # path : 
  output_res  : 24  # temporal resolution of output variables in hours (i.e., model outputs given variable names every X hours)
  output_vars  : ["bathymetry", "ground_temperature_distribution", "thaw_depth"]  # list of output variables