# dataset parameters
dataset_parameters:
  database_folder: 'database/datasets'  # datasets location


# model settings
model:
  # nx: 100  # number of points in x-direction
  longitude: -143.7  # longitude of the study site
  latitude: 70.13  # latitude of the study site
  time_start: '08-01-2020'  # MM-DD-YY starting time (if -1 take entire dataset)
  time_end : '08-10-2020' # MM-DD-YY stopping time (if -1 take entire dataset)
  timestep: 1              # size of timesteps (in hours)
  call_xbeach_inter:  168  #  xbeach is called during inter-storm periods every X (wrapper) timesteps (default: 168, i.e. 1 week)
  time_zone_diff: -8  # [hours] relative difference in hours with respect to UTC. For Alaska equals -8.


# wrapper parameters:
wrapper:
  dir:  'runs/...'         # location of model run
  sea_ice_threshold: 0.15  # Only run xbeach if sea ice fraction is below threshold, otherwise assume all wave action attenuated


# bathymetry parameters
bathymetry:
  xfile:   'x.grd'   # file used for the grid (x-direction)
  depfile: 'bed.dep'  # file used for the bed
  grid_orientation: 88.14  # [degrees], grid orientation with respect to east. The current orientation is calculated in the 'generate_bathymetry.ipynb' notebook

  # schematized bathymetry parameters
  with_schematized_bathymetry :  True  # whether or not to generate a schematized bathymetry upon initialization
  bluff_flat_length           :  100  # [m] length of the flat attached to the crest of the bluff
  bluff_height                :  12  # [m] height of the bluff
  bluff_slope                 :  0.5  # [-] slope of the bluff, i.e., height/width
  beach_width                 :  12.5  # [m] width of the beach
  beach_slope                 :  0.1  # [-] slope of the beach, i.e., height/width
  nearshore_max_depth         :  3  # [m] maximum depth of the nearshore
  nearshore_slope             :  0.03  # [-] slope of the nearshore section, i.e., height/width
  offshore_max_depth          :  5  # [m] maximum offshore depth
  offshore_slope              :  0.007  # [-] slope of the offshore section, i.e., height/width
  continental_flat_width      :  400  # [m] width of the continental flat section
  with_artificial             :  True  # whether or not to extend to bathymetry with an artificial depth increase (if required by xbeach)
  artificial_max_depth        :  10  # [m] maximum depth of the artificial section (wave heights in dataset are defined at a depth of 10m, so that value is recommended)
  artificial_slope            :  0.02  # [-] slope of the artificial section, i.e., height/width
  N                           :  100 # number of points of each section


# xbeach parameters
xbeach:
  # general settings
  with_xbeach: True  # include the xbeach module in the model, default true
  version: '1.24'  # version of xbeach used

  # grid settings
  tstop:   '3600'    # length of xbeach simulation (in seconds), should be the same as model.timestep
  thetamin: '-90'  # minimum angle
  thetamax: '90'   # maximum angle
  dtheta:   '15'     # bin width

  # hydrodynamics settings
  wbctype: 'jons'   # type of wave boundary condition
  bcfile:  'filelist.txt'  # file ocntaining the bc specifications
  rho_sea_water : 1025  # [kg/m3] density (sea) water
  visc_kin      : 0.000006  # [m2/s] kinematic viscosity sea water (placeholder)

  # sediment properties
  reposeangle: 35  # [degrees] angle of repose used in xbeach (placeholder)
  dryslp: 35  # [degrees] Critical avalanching slope above water (dz/dx and dz/dy) (placeholder)
  wetslp: 35  # [degrees] Critical avalanching slope below water (dz/dx and dz/dy) (placeholder)
  D50: 0.00190  # [m] mean grain size, value from erikson data (at waterline, a few km westward of the transect) 
  rho_solid: 2650  # [kg/m3] density of sediment particles
  bedfriccoef: 0.01  # [-] bed friction coefficient (placeholder)


# thermal moodel parameters
thermal:
  # general
  with_solar                  : True  # include short wave solar radiation in thermal computation step
  with_longwave               : True  # include longwave radiation (incoming & outgoining) in thermal computation step
  with_latent                 : True  # include latent heat in thermal computation step\
  with_solar_flux_calculator  : True  # include solar flux calculator in the computation (if False, the every surface is treated as flat); requires 'with_solar: True'
  
  # guess for convective heat transfer from water
  with_convective_transport_water_guess : True  # include a guess of convective heat transfer from water in thermal computation step. If False, a more sophisticated computation is performed
  hc_guess : 500  # [W/m2/K], guess for the convective heat transfer coefficient from water (from Kobayashi et al, 1999)

  # model properties
  dt: 2  # [s] timestep used in the thermal model on the temporal subgrid
  grid_resolution : 30  # number of points for each 1D thermal model
  max_depth       : 3  # [m], the maximum depth of the 1D thermal model
  # dz_max          : 10 # [m/s/m] Maximum bed level change due to avalanching
  T_melt          : 273.15  # [K] Melting temperature at the interface of water/air and bluff

  # water properties
  wl_switch       : 0  # [m], water level relative to outputted local water level at which is switched from wet to dry (positive means higher than output water level)
  L_water_ice     : 334000000 # [J/m3] latent heat of fusion water-ice
  rho_water       : 1000  # [kg/m3] water density
  rho_ice         : 971  # [kg/m3] density ice
  # c_sea_water     : ...  # [J/K] heat capacity for seawater
  # k_sea_water     : ... #  [W/m/K] thermal conductivity for sea water

  # soil properties
  with_density      : False  # whether or not to used density in the temperature distribution calculations. formulations with density have not been implemented yet.
  rho_soil_frozen   : 1500   # [kg/m3] density frozen soil, placeholder (placeholder)
  rho_soil_unfrozen : 1500   # [kg/m3] density unfrozen soil, placeholder (placeholder)
  nb              : 0.65  # [-] ground ice content (Ravens et al, 2023: 0.65 - 0.45)
  c_soil_frozen   : 4600000  # [J/K/m3] volumetric heat capacity for frozen soil (Ravens et al, 2023)
  c_soil_unfrozen : 7000000  # [J/K/m3] volumetric heat capacity for unfrozen soil (Ravens et al, 2023)
  k_soil_frozen_min   : 0.7  # [W/m/K] minimum thermal conductivity for frozen soil (Ravens et al, 2023: 0.7 - 2.7)
  k_soil_frozen_max   : 2.7  # [W/m/K] maximum thermal conductivity for frozen soil (Ravens et al, 2023: 0.7 - 2.7)
  k_soil_unfrozen_min : 0.6  # [W/m/K] minimum thermal conductivity for unfrozen soil (Ravens et al, 2023: 0.6 - 1.5)
  k_soil_unfrozen_max : 1.5  # [W/m/K] maximum thermal conductivity for unfrozen soil (Ravens et al, 2023: 0.6 - 1.5)
  depth_constant_k    : 1  # [m] depth at which k reaches its maximum value. k remains constant below this depth (Ravens, MATLAB script)
  geothermal_gradient : 0.025  # [K/m] geothermal gradient, used as the boundary condition at the bottom of each 1D model


# output
output:
  output_res  : 24  # temporal resolution of output variables in hours (i.e., model outputs given variable names every X hours)
  output_vars  : ["bathymetry", "ground_temperature_distribution", "thaw_depth"]  # list of output variables